version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  orders-db:
    image: postgres:15
    environment:
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
      POSTGRES_DB: orders
    volumes:
      - orders-data:/var/lib/postgresql/data

  payments-db:
    image: postgres:15
    environment:
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
      POSTGRES_DB: payments
    volumes:
      - payments-data:/var/lib/postgresql/data

  orders-service:
    build: ./services/orders
    environment:
      PORT: 8081
      DATABASE_URL: postgres://orders:orders@orders-db:5432/orders?sslmode=disable
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - orders-db
      - rabbitmq
    ports:
      - "8081:8081"

  payments-service:
    build: ./services/payments
    environment:
      PORT: 8082
      DATABASE_URL: postgres://payments:payments@payments-db:5432/payments?sslmode=disable
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - payments-db
      - rabbitmq
    ports:
      - "8082:8082"

  frontend:
    build: ./frontend
    environment:
      PORT: 8083
    ports:
      - "8083:8083"

  gateway:
    build: ./services/gateway
    environment:
      PORT: 8080
      ORDERS_URL: http://orders-service:8081
      PAYMENTS_URL: http://payments-service:8082
      FRONTEND_URL: http://frontend:8083
      CATALOG_URL: http://catalog-service:8084
      USERS_URL: http://users-service:8085
    depends_on:
      - orders-service
      - payments-service
      - frontend
      - catalog-service
      - users-service
    ports:
      - "8080:8080"

  catalog-db:
    image: postgres:15
    environment:
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
      POSTGRES_DB: catalog
    volumes:
      - catalog-data:/var/lib/postgresql/data

  catalog-service:
    build: ./services/catalog
    environment:
      PORT: 8084
      DATABASE_URL: postgres://catalog:catalog@catalog-db:5432/catalog?sslmode=disable
    depends_on:
      - catalog-db
    ports:
      - "8084:8084"

  users-service:
    build: ./services/users
    environment:
      PORT: 8085
      DATABASE_URL: postgres://users:users@users-db:5432/users?sslmode=disable
      JWT_SECRET: supersecret
    depends_on:
      - users-db
    ports:
      - "8085:8085"

  users-db:
    image: postgres:15
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: users
      POSTGRES_DB: users
    volumes:
      - users-data:/var/lib/postgresql/data

volumes:
  orders-data:
  payments-data:
  catalog-data:
  users-data:

